[package]
name = "zip_cracker"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "2.2"
rayon = "1.10"
num_cpus = "1.16"
infer = "0.16"       # 文件类型检测库
clap = { version = "4.5", features = ["derive"] }  # 命令行参数解析

[profile.release]
opt-level = 3
lto = true
